# Generated by Django 5.2.4 on 2025-09-10 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id_cart", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCart",
            fields=[
                ("id_itemcart", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="carrito.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item del Carrito",
                "verbose_name_plural": "Items del Carrito",
                "unique_together": {("product", "cart")},
            },
        ),
    ]
