# Generated by Django 5.2.4 on 2025-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
