# Generated by Django 4.2.26 on 2025-11-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customer_email"),
        ("catalogo", "0004_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Búsqueda de Producto",
                "verbose_name_plural": "Búsquedas de Productos",
            },
        ),
        migrations.CreateModel(
            name="ProductClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="catalogo.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clic de Producto",
                "verbose_name_plural": "Clics de Productos",
            },
        ),
    ]
