# Generated by Django 4.2.26 on 2025-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0006_product_category_en_product_category_es_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
