# Generated by Django 4.2.26 on 2025-11-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0007_alter_product_name_alter_product_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category_es",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_es",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
