# Generated by Django 5.2.4 on 2025-09-10 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carrito", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id_order", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Pagado", "Pagado"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="carrito.cart"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden",
                "verbose_name_plural": "Órdenes",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id_payment_method",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=50)),
                ("card_number", models.CharField(max_length=16)),
                ("expiration_date", models.CharField(max_length=5)),
                ("security_code", models.CharField(max_length=3)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de Pago",
                "verbose_name_plural": "Métodos de Pago",
            },
        ),
    ]
