# Generated by Django 5.2.4 on 2025-09-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id_order_item", models.AutoField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="ordenes.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Orden",
                "verbose_name_plural": "Items de Orden",
            },
        ),
    ]
