# Generated by Django 5.2.5 on 2025-08-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_remove_product_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='id',
        ),
        migrations.AddField(
            model_name='itemcart',
            name='id_itemcart',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
