# Generated by Django 5.2.4 on 2025-09-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_itemcart_id_itemcart_id_itemcart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={},
        ),
    ]
