# Generated by Django 5.2.4 on 2025-09-02 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_cart_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcart",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.cart",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemcart",
            unique_together={("product", "cart")},
        ),
    ]
